function main() {}

try {
  main();
} catch (e) {
  console.log(e);
}
